import type { MediaAsset, Project } from '../types/editor';

export const SAMPLE_ASSETS: MediaAsset[] = [
  {
    id: 'asset-video-1',
    name: 'Natureza & Montanhas',
    type: 'video',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    duration: 15,
    thumbnail: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=400&q=80',
    width: 1920,
    height: 1080,
  },
  {
    id: 'asset-video-2',
    name: 'Ondas & Oceano',
    type: 'video',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    duration: 15,
    thumbnail: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=400&q=80',
    width: 1920,
    height: 1080,
  },
  {
    id: 'asset-video-3',
    name: 'Vida Urbana & Luzes',
    type: 'video',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    duration: 12,
    thumbnail: 'https://images.unsplash.com/photo-1477959858617-67f30bc75b82?auto=format&fit=crop&w=400&q=80',
    width: 1920,
    height: 1080,
  },
  {
    id: 'asset-video-4',
    name: 'Aventura & Estrada',
    type: 'video',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
    duration: 15,
    thumbnail: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=400&q=80',
    width: 1920,
    height: 1080,
  },
  {
    id: 'asset-audio-1',
    name: 'Upbeat Lo-Fi Chill',
    type: 'audio',
    url: 'https://actions.google.com/sounds/v1/ambiences/coffee_shop.ogg',
    duration: 20,
  },
  {
    id: 'asset-audio-2',
    name: 'Eletrônica Energética',
    type: 'audio',
    url: 'https://actions.google.com/sounds/v1/science_fiction/force_field_hum.ogg',
    duration: 18,
  },
  {
    id: 'asset-audio-3',
    name: 'Transição Whoosh FX',
    type: 'audio',
    url: 'https://actions.google.com/sounds/v1/weapons/laser_gun_shot.ogg',
    duration: 3,
  }
];

export const INITIAL_PROJECT: Project = {
  id: 'proj-default-1',
  name: 'Meu Vídeo no Android',
  aspectRatio: '9:16',
  resolution: '1080p',
  fps: 30,
  duration: 18,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  videoClips: [
    {
      id: 'clip-1',
      assetId: 'asset-video-1',
      name: 'Montanhas',
      type: 'video',
      url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
      thumbnail: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=400&q=80',
      startOffset: 0,
      duration: 6,
      timelineStart: 0,
      speed: 1,
      volume: 80,
      brightness: 0,
      contrast: 10,
      saturation: 20,
      filter: 'cinematic',
      rotation: 0,
      scale: 1,
    },
    {
      id: 'clip-2',
      assetId: 'asset-video-2',
      name: 'Oceano',
      type: 'video',
      url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
      thumbnail: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=400&q=80',
      startOffset: 0,
      duration: 6,
      timelineStart: 6,
      speed: 1,
      volume: 100,
      brightness: 5,
      contrast: 5,
      saturation: 15,
      filter: 'vibrant',
      rotation: 0,
      scale: 1,
    },
    {
      id: 'clip-3',
      assetId: 'asset-video-3',
      name: 'Cidade',
      type: 'video',
      url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
      thumbnail: 'https://images.unsplash.com/photo-1477959858617-67f30bc75b82?auto=format&fit=crop&w=400&q=80',
      startOffset: 0,
      duration: 6,
      timelineStart: 12,
      speed: 1,
      volume: 90,
      brightness: 0,
      contrast: 15,
      saturation: 10,
      filter: 'cyberpunk',
      rotation: 0,
      scale: 1,
    }
  ],
  audioClips: [
    {
      id: 'audio-1',
      assetId: 'asset-audio-1',
      name: 'Trilha Sonora Lo-Fi',
      url: 'https://actions.google.com/sounds/v1/ambiences/coffee_shop.ogg',
      duration: 18,
      timelineStart: 0,
      volume: 75,
      fadeDuration: 1.5,
    }
  ],
  textOverlays: [
    {
      id: 'text-1',
      text: '✨ OpenCut no Android',
      timelineStart: 0.5,
      duration: 4.5,
      fontSize: 28,
      color: '#ffffff',
      backgroundColor: 'rgba(15, 23, 42, 0.75)',
      fontFamily: 'Plus Jakarta Sans',
      fontWeight: '700',
      positionX: 50,
      positionY: 20,
      animation: 'pop',
    },
    {
      id: 'text-2',
      text: '🎬 Edição Móvel & Responsiva',
      timelineStart: 6.2,
      duration: 5,
      fontSize: 24,
      color: '#38bdf8',
      backgroundColor: 'rgba(0, 0, 0, 0.65)',
      fontFamily: 'Plus Jakarta Sans',
      fontWeight: '600',
      positionX: 50,
      positionY: 80,
      animation: 'slide-up',
    }
  ]
};
